spring:
  application:
    name: budgy-backend

  datasource:
    url: jdbc:mysql://localhost:3306/budgy_db?createDatabaseIfNotExist=true
    username: root
    password: root0107

  jpa:
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.budgy.backend: DEBUG
    org.hibernate.SQL: DEBUG